---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность авторизоваться
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность создать игру с ботом без регистрации
  - Пользователь должен иметь возможность создать игру со случайным пользователем
  - Пользователь должен иметь возможность создать турнир
  - Пользователь должен иметь возможность создать игру с другом по ссылке-приглашению
  - Пользователь во время игры должен иметь возможность видеть как  соперник пишет код
  - Пользователь должен победить при правильном на писании задачи быстрее соперника 
  - Пользователь должен проиграть, если соперник выполняет задачу раньше 
  - Пользователь должен иметь возможность сдаться в игре
non-functional:
  - Удобство использования сайта для пользователей
  - Оптимизация скорости работы сайта
  - Обеспечение безопасности и защиты данных пользователей
  - Удобство использования сайта на мобильных устройствах
  - Тестирование и совместимость сайта с последними версиями браузеров
  - Способность сайта обрабатывать большое количество трафика, например, 1000 одновременных пользователей
implicit:
  - Привлекательный дизайн сайта
  - Легкость использования даже для непрофессиональных пользователей
